---
  - name: Ensure nginx is installed and in working state
    apt:
      name: nginx
      
  - name: start nginx
    service:
      name: nginx
      state: started
    
  - name: copy the content of the web site
    copy:
      src: /Users/home/Documents/ica0002/roles/nginx/files/uwsgi_app.cfg
      dest: /etc/nginx/sites-enabled/default
    become: yes
    notify: restart nginx
      
    
