---
  - name: Ensure nginx is installed and in working state
    apt:
      name: nginx
      update_cache: yes
      
  - name: start nginx
    service:
      name: nginx
      state: started

  - name: create directory
    file:
      path: /home/ubuntu/static-site
      state: directory
      remote_src: yes
    
  - name: create a nginx config file with the contents
    copy:
      dest: "/home/ubuntu/static_site.cfg"
      content: |
        server {
          listen 80 default_server;
          listen [::]:80 default_server;
          root /home/ubuntu/static-site;
          server_name _;
          location / {
            try_files $uri $uri/ =404;
          }
        } 
       
  - name: copy the nginx config file and restart nginx
    copy:
      src: /home/ubuntu/static_site.cfg
      dest: /etc/nginx/sites-available/static_site.cfg
      remote_src: yes
    become: yes
  
  - name: create symlink
    file:
      src: /etc/nginx/sites-available/static_site.cfg
      dest: /etc/nginx/sites-enabled/default
      state: link
      remote_src: yes
    become: yes
  
  - name: copy the content of the web site
    copy:
      src: /Users/home/Documents/ica0002/roles/nginx/files/index.html
      dest: /home/ubuntu/static-site
      remote_src: no  
    
  - name: copy the nginx config file and restart ngnix
    copy:
      src: /Users/home/Documents/ica0002/roles/nginx/files/uwsgi_app.cfg
      dest: /etc/nginx/sites-enabled/default
    become: yes
    notify: restart nginx