- name: Ensure nginx is installed and in working state
  apt: 
    name: nginx  

- name: Copy Nginx default config to sites-enabled
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started 
    enabled: yes
  become: yes