---
  - name: Install uWSGI packages
    apt:
      pkg:
      - uwsgi
      - uwsgi-plugin-python3
      - python3-pymsql
      
  - name: Start uWSGI
    service:
      name: uwsgi
      state: started
      
  - name: copy the uwsgi config file
    template:
      src: /Users/home/Documents/ica0002/roles/uwsgi/templates/agama.ini
      dest: /etc/uwsgi/apps-enabled/agama.ini
    become: yes
    notify: restart uwsgi
      
    

