---
- name: Collect information about all VMs
  hosts: all
  tasks:
    - setup:

- name: Ansible connection test
  hosts: all
  roles:
    - test_connection

- name: Setup
  hosts: all
  become: yes
  roles:
    - init

- name: DNS
  hosts: dns_servers
  become: yes
  roles:
    - bind
  tags: bind

- name: DNS Resolved
  hosts: all
  become: yes
  roles:
    - dns_resolve
  tags: dns_resolve

- name: Configure Nginx
  hosts: all
  become: yes
  roles:
    - nginx
  tags: nginx

- name: Configure Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
  tags: prometheus

- name: db servers
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
  tags: mysql

- name: Internal Machine Play
  hosts: internal_vm
  become: yes
  roles:
    - users
    #- grafana
    - docker
    - grafana_docker
    - nginx_exporter
    - influxdb
    - rsyslog
    - backup
    - pinger
  tags:
    - internal

- name: Application Machine Play
  hosts: application_vms
  become: yes
  roles:
    - docker
    - agama_docker
    - haproxy
    - keepalived
    - backup
    - mysql_exporter
    - nginx_exporter
    - bind_exporter
    - node_exporter
    - rsyslog
  tags:
    - application