- name: Install InfluxDB and Telegraf
  hosts: influxdb
  gather_facts: false
  become: yes
  roles:
    - influxdb

- name: Configure Rsyslog
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - rsyslog

- name: Transfer and setup pinger sciprt
  hosts: pinger
  gather_facts: false
  become: yes
  roles:
    - pinger

