---
  - name: Setup
    hosts: all
    become: yes
    roles:
       - init

  - name: Install Node Exporters
    hosts: all
    become: yes
    roles:
      - node_exporter

  - name: Configure Prometheus
    hosts: prometheus
    become: yes
    roles:
      - prometheus
