- name: Reconfigure DNS
  hosts: dns_servers
  gather_facts: true
  become: yes
  roles:
    - bind
  tags: bind

- name: Configure backups
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - backup
  tags: backup