
- name: Setup Nginx, Agama, uWSGI and MySQL setup role
  hosts: app_servers
  gather_facts: false
  become: yes
  roles:
    - nginx

- name: Setup MySQL
  hosts: db_servers
  gather_facts: false
  become: yes
  roles:
    - mysql

- name: Setup DNS server
  hosts: dns_servers
  gather_facts: true
  become: yes
  roles:
    - bind


- name: Setup Prometheus
  hosts: prometheus
  gather_facts: false
  become: yes
  roles:
    - prometheus

- name: Setup Node exporters
  hosts: node_exporters
  gather_facts: false
  become: yes
  roles:
    - node_exporter

- name: Setup Nginx exporter
  hosts: all
  become: yes
  roles:
    - nginx_exporter
 
- name: Setup exporter
  hosts: dns_servers
  gather_facts: false
  become: yes
  roles:
    - bind_exporter
 
- name: Setup MySQL exporter
  hosts: db_servers
  gather_facts: false
  become: yes
  roles:
    - mysql_exporter

# Commented out since Lab 12 - Docker
#- name: Setup Grafana
#  hosts: grafana
#  gather_facts: false
#  become: yes
#  roles:
#    - grafana

- name: Setup backup facility
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - backup
