---
  - name: Creating system user
    user:
      name: agama
      comment: Web app user
      system: yes
      
  - name: Create install directory
    file:
      state: directory
      path: /opt/agama
      owner: agama
      group: agama
      mode: 0755
      
  - name: Ensure python3-flask-sqlalchemy is installed and in working state
    apt:
      name: python3-flask-sqlalchemy
      update_cache: yes
      
  - name: Download agama.py
    get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
      dest: /opt/agama
      mode: 0755
      
    

