---
- name: Add the user "backup" and generate keys
  user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
# Add MySQL backup user and MySQL cnf file
- name: Create MySQL backup user
  mysql_user:
    name: "{{ mysql_backup_user }}"
    password: "{{ mysql_backup_pass }}"
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  when: inventory_hostname == "vugarg-2"

- name: Copy MySQL configuration file
  template:
    src: backup.my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    mode: '0400'
  when: inventory_hostname == "vugarg-2"
  
#- name: Grafana directory
 # file:
  #  name: /opt/docker/grafana
   # state: directory
    #owner: "472"
    #group: "472"
    #recurse: true

- name: Add the user to the Grafana group on the vugarg-3
  user:
    name: backup
    groups: grafana
  when: inventory_hostname == "vugarg-3"

- name: Add backup to mysql group
  user:
    name: backup
    groups: mysql
  when: inventory_hostname == "vugarg-2"

- name: Create backup, restore and scripts directories
  file:
    path: /home/backup/{{ item }}
    state: directory
    owner: backup
    group: backup
    mode: '0755'
  loop:
    - backup
    - restore

- name: Install Duplicity
  apt:
    name: duplicity

- name: Copy crontab to vugarg-2
  template:
    src: crontab.vm2.j2
    dest: /etc/cron.d/backup
  when: inventory_hostname == "vugarg-2"

- name: Copy crontab to vugarg-3
  template:
    src: crontab.vm3.j2
    dest: /etc/cron.d/backup
  when: inventory_hostname == "vugarg-3"