---
  - name: Creating linux users
    user:
      name: roman
      name: juri

  - name: SSH public key juri
    authorized_key:
      user: juri
      state: present
      key: https://github.com/hudolejev.keys

  - name: SSH public key roman
    authorized_key:
      user: roman
      state: present
      key: https://github.com/romankuchin.keys
