---
- name: Install Prometheus
  apt:
    name: 
      - prometheus

- name: Configure Prometheus
  template: 
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: 
    - Restart Prometheus
    - restart Nginx
  become: yes

- name: Configure Prometheus' web path
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: 
    - Systemctl daemon-reload
    - Restart Prometheus 
    - restart Nginx

- name: Execute handlers preemptively
  meta: flush_handlers

- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes
  become: yes 