---
- name: Install bind
  apt:
    name: 
      - bind9
      - python3-dnspython 
    state: latest

- name: copy the options config file
  template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Bind zone config
  template:
    src: ../templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local    
  notify: restart bind9
  when: inventory_hostname in groups['dns_masters']

- name: Bind slave zone config
  template:
    src: ../templates/named.conf.local.slave.j2
    dest: /etc/bind/named.conf.local     
  notify: restart bind9
  when: inventory_hostname in groups['dns_slaves']

- name: DNS Zone
  template:
    src: ../templates/db.vglax.j2
    dest: /var/lib/bind/db.vglax.io
    force: no
  notify: 
    - Reload rndc
    - Sync rndc
  when: inventory_hostname in groups['dns_masters']
  
- name: Execute handlers
  meta: flush_handlers

- name: Add an A record
  nsupdate:
    key_algorithm: "hmac-sha256"
    key_name: "dns_update"
    key_secret: "{{ns_update_secret}}"
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ fqdn }}."
    record: "{{ item['subdomain'] }}.{{ fqdn }}."
    value: "{{ item['ip'] }}"
    type: "A"
  loop: "{{ a_records }}"
  when: inventory_hostname == groups['dns_masters'][0]

- name: Add CNAME record
  nsupdate:
    key_algorithm: "hmac-sha256"
    key_name: "dns_update"
    key_secret: "{{ ns_update_secret }}"
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ fqdn }}."
    record: "{{ item['cname'] }}.{{ fqdn }}."
    value: "{{ item['real'] }}.{{ fqdn }}."
    type: "CNAME"
  loop: "{{ dns_cnames }}"
  when: inventory_hostname == groups['dns_masters'][0]

- name: Start service bind9, if not started
  service:
    name: bind9
    state: started
    enabled: yes