- name: Set DNS Server to vm2
  lineinfile:
   insertafter: '^nameserver 127.0.0.53'
   line: nameserver {{ hostvars['vugarg-2']['ansible_default_ipv4']['address'] }}
   path: /etc/resolv.conf

- name: Install bind
  apt:
    pkg: bind9
    state: present

- name: Copy named.conf.masterzone
  template:
    src: named.conf.masterzone.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9

- name: Make zones Directory
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: 0750

- name: Copy forward file
  template:
    src: db.forward.j2
    dest: /etc/bind/zones/db.forward
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9

- name: Copy reverse file
  template:
    src: db.reverse.j2
    dest: /etc/bind/zones/db.reverse
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9

- name: Copy local reverse file
  template:
    src: db.local.j2
    dest: /etc/bind/zones/db.local_reverse
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9

- name: check if firewalld is running
  command: systemctl is-active firewalld
  register: firewalld_result
  changed_when: False
  ignore_errors: True

- name: Open firewall port
  firewalld:
   service: dns
   permanent: true
   state: enabled
   immediate: yes
  when: firewalld_result.stdout == "active"

- name: Copy resolv.conf file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: bind
    mode: 0640
  notify: restart bind9